name = "FlexIK"
uuid = "13853d61-a6f1-4272-bc93-0a9a4343e895"
authors = ["Andy Park <andypark@theaiinstitute.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
